### ISSUE TITLE
Potential additional copying in the constructor.

### ISSUE THREAD

**Issue by safocl** [trustwallet/wallet-core#2892] opened 2023-01-26 09:10 UTC
**Describe the bug**
[Lines](https://github.com/trustwallet/wallet-core/blob/1709e798b68a93fb0ed311a9fc97ef21ba7eebc4/src/EOS/Transaction.h#L39) like this potentially add to extra copying with rvalue args.
`Extension(uint16_t type, const Data& buffer) : type(type), buffer(buffer) { }`

Clang-tidy recommends:
> pass by value and use std::move

This discussion has already taken place: [here](https://stackoverflow.com/a/51706522/15599118)
I tried it, and it's all really: [link](https://godbolt.org/z/36P4er4co)

It is better to use this instead:
`Extension(uint16_t type, Data buffer) : type(type), buffer(std::move(buffer)) { }`

**Comment by Milerius** [comment] 2023-01-26 12:45
Yes there is a lot of code like that ATM, however the performance penalty is not dramatic, it's not a bug, just a sub optimization. Note that we are moving some code to Rust so that effort is probably not worth it, issues in the backlog are the one that we consider important at the moment. Closing for now, you can directly open pull request for such fix

**Closed by Milerius** 2023-01-26 12:45 UTC
Labels: bug

**Comment by safocl** [comment] 2023-01-26 14:04
> it's not a bug, just a sub optimization.

yes -- i miss click on the issue type. -- it is performance improvement.
