### ISSUE TITLE
Support for Jettons on TON blockchain

### ISSUE THREAD

**Issue by snowkidind** [trustwallet/wallet-core#3898] opened 2024-06-14 14:41 UTC
Gentlemen thanks for supporting TON, there are many wallets on the TON ecosystem that use a 24 word mnemonic but none that use a 12 word. 

Further, the method you used to generate the wallet is unknown, and because of this the wallet address you derived from your keygen method does not support Jettons. This becomes an issue when a TON user decides to send Jettons to the TON address the trust wallet generates. 

Another wallet has added an import from private key feature to their wallet but alas, the common method is not being used in trust causing peoples funds (like JUSDT) to be lost in the mix.

Can you at a minimum devolve the method you used to create the twelve word mnemonic or create an escape path for mistakenly sent jettons to a trust wallet? 

Thanks

See Also:
https://github.com/mytonwalletorg/mytonwallet/issues/62

**Comment by ronaldoguedess** [comment] 2024-06-15 02:18
Do you mean that the Trust Wallet method doesn't support Jettons? There is a method in their examples; I think it works. However, the seed generated by Trust Wallet is not compatible with TON's wallets. Nevertheless, it's still possible to import using the private key.

Soon I will be launching the TON Network on the ECOIN Wallet, where you will be able to use the private key as well as 12 or 24 words.

**Comment by snowkidind** [comment] 2024-06-15 04:31
I dont believe trust wallet supports jettons, unless it's recent. 

Access to jettons via whatever method they used to derive a private key  / address in trust wallet is not currently accessible using any known methods for example, using 

```
      const provider = tonweb.provider
      const seed = await mnemonicToSeed([mnemonic]) // 12 word mnemonic
      const keyPair = tonweb.utils.nacl.sign.keyPair.fromSeed(seed)

      const wallet = new tonweb.wallet.all.v4R2(provider, {
        publicKey: keyPair.publicKey,
        wc: 0
      })

      console.log(keyPair.secretKey.toString())

```

**Comment by ronaldoguedess** [comment] 2024-06-15 04:40
The Trust Wallet core supports this, but the Trust Wallet App does not. As I mentioned earlier, the ECOIN Wallet will soon introduce TON Network, with support for private keys, a 12-word, or 24-word seed phrase, and also Jettons.

**Comment by snowkidind** [comment] 2024-06-15 04:41
bro stop spamming the githubs this is not an appropriate channel

**Comment by ronaldoguedess** [comment] 2024-06-15 04:54
> bro stop spamming the githubs this is not an appropriate channel

You asked something, I just said I will launch what you need to solve your problem, sorry if it bother your.

I understand your frustration. I just said I will launch what you need to solve your problem, and I apologize if my approach seemed spammy.

**Comment by snowkidind** [comment] 2024-06-15 04:54
developer community can read the instructions, we dont need to be battered by repeat information. please consider this moving forward.

**Comment by Milerius** [comment] 2024-06-15 04:56
Hello, we will begin the development of Ton Jettons in TrustWallet App next week, and will also add Ton Connect.

In terms of wallet compatibility, it's important to remember that TrustWallet is a multichain wallet that relies on the widely used standards for generating seed and private keys: BIP39 and BIP44. Regrettably, the Ton architecture has adopted a different approach that we cannot support without compromising compatibility for our users. Nevertheless, it will still be possible to import the private key, and you should be able to see your Ton Jettons within the next week. Additionally, you'll be able to access Ton Ecosystem DApps directly within the TrustWallet app.

**Comment by ronaldoguedess** [comment] 2024-06-15 04:57
Read about the seed: https://github.com/trustwallet/wallet-core/issues/3188

**Comment by Milerius** [comment] 2024-06-15 04:59
> Read about the seed: #3188

We understand the request, and to ensure complete transparency, incorporating this into the app for smooth user experience would necessitate significant rework and architectural design changes. This is specifically to support a single blockchain with a unique seed generation method. While we're not ruling it out, it's not an update you can expect in the near future.

**Comment by ronaldoguedess** [comment] 2024-06-15 05:08
> Hello, we will begin the development of Ton Jettons in TrustWallet App next week, and will also add Ton Connect.
> 
> In terms of wallet compatibility, it's important to remember that TrustWallet is a multichain wallet that relies on the widely used standards for generating seed and private keys: BIP39 and BIP44. Regrettably, the Ton architecture has adopted a different approach that we cannot support without compromising compatibility for our users. Nevertheless, it will still be possible to import the private key, and you should be able to see your Ton Jettons within the next week. Additionally, you'll be able to access Ton Ecosystem DApps directly within the TrustWallet app.

That's great news! 👏🏻 You're absolutely correct; it could affect the compatibility for TW users. What's your plan regarding the Webprovider? Are you considering adding support for TON dapps on the Trust Web3 Provider (https://github.com/trustwallet/trust-web3-provider), or will you opt to implement Ton Connect (https://github.com/trustwallet/trust-web3-provider/issues/529)?

Also, considering that TON Connect currently lacks a JAVA/KOTLIN library, are you planning to develop something to address this gap?

**Comment by Milerius** [comment] 2024-06-15 05:09
> > Hello, we will begin the development of Ton Jettons in TrustWallet App next week, and will also add Ton Connect.
> > In terms of wallet compatibility, it's important to remember that TrustWallet is a multichain wallet that relies on the widely used standards for generating seed and private keys: BIP39 and BIP44. Regrettably, the Ton architecture has adopted a different approach that we cannot support without compromising compatibility for our users. Nevertheless, it will still be possible to import the private key, and you should be able to see your Ton Jettons within the next week. Additionally, you'll be able to access Ton Ecosystem DApps directly within the TrustWallet app.
> 
> That's great news! 👏🏻 You're absolutely correct; it could affect the compatibility for TW users. What's your plan regarding the Webprovider? Are you considering adding support for TON dapps on the Trust Web3 Provider (https://github.com/trustwallet/trust-web3-provider), or will you opt to implement Ton Connect ([trustwallet/trust-web3-provider#529](https://github.com/trustwallet/trust-web3-provider/issues/529))?
> 
> Also, considering that TON Connect currently lacks a JAVA/KOTLIN library, are you planning to develop something to address this gap?

Those choice(s) will be made by @y3fers0n & @gastonm5 who are leading this initative.

**Comment by ffrediani** [comment] 2024-06-21 17:33
@Milerius would you comment about this issue regarding derivation path that seems to be different in TrustWallet ? I guess this would have no issues regarding compromising compatibility for our users. It would be just a choice to be made like other wallets did and be the same so an user importing their words into either wallet funds will appear as expected.

If is necessary a significant architectural changes than so be it. At the end at the user's benefit to have a more seamless app for their choice and not have to worry about details like derivation path, private key etc.

Importing the private key is always something undesirable because it needs further steps to get this information and it is not as friendly as importing 12 or 24 words. It can be a temporary solution, but not definitive.

Good to see there is work going on this topic by TW Team.

**Comment by Doferesouleymane** [comment] 2024-06-23 00:16
Cool@285

**Comment by Moormemar** [comment] 2024-06-24 19:46
Hi

در تاریخ یکشنبه ۲۳ ژوئن ۲۰۲۴،‏ ۰۳:۴۶ Doferesouleymane <
***@***.***> نوشت:

**Comment by Moormemar** [comment] 2024-06-24 19:46
Hi

در تاریخ دوشنبه ۲۴ ژوئن ۲۰۲۴،‏ ۲۳:۱۶ Moorteza ***@***.***> نوشت:

**Comment by ronaldoguedess** [comment] 2024-07-12 02:58
@y3fers0n @gastonm5 
Considering that TON Connect currently lacks a JAVA/KOTLIN library, are you planning to develop something to address this gap?

Btw, any news related to the TON?

**Comment by satoshiotomakan** [comment] 2024-07-12 07:39
Hi @snowkidind, could you please clarify, did you try to send Jettons to an initialized TON address (ever held funds)? If I'm not mistaken, the wallet needs to be initialized so you can transfer Jettons to the address.
We actively work on Jetton support, and just recently added two helper functions in WalletCore to generate Jetton address to check the balance: https://github.com/trustwallet/wallet-core/pull/3922 (please take a look at unit tests added)
Also we already support Jetton transfer: https://github.com/trustwallet/wallet-core/pull/3331 (take a look at unit tests added)
Soon Trust Wallet apps will allow to transfer Jettons
> Further, the method you used to generate the wallet is unknown, and because of this the wallet address you derived from your keygen method does not support Jettons. This becomes an issue when a TON user decides to send Jettons to the TON address the trust wallet generates.

**Comment by satoshiotomakan** [comment] 2024-07-12 07:50
@snowkidind @ronaldoguedess @ffrediani
The problem is that TON 24-words mnemonic doesn't follow BIP39 standard. It requires to implement a TON specific derivation method, and derivation path doesn't even play a role in this derivation. Please also note that it only allows to derive `ONE` account, but Trust Wallet (and WalletCore) is multi-chain oriented.
> would you comment about this issue regarding derivation path that seems to be different in TrustWallet ? I guess this would have no issues regarding compromising compatibility for our users. It would be just a choice to be made like other wallets did and be the same so an user importing their words into either wallet funds will appear as expected.

But we consider adding support for TON 24-words specific mnemonic for TON chain only in the near future, and if you import it, you can only see TON account. The task is in our roadmap, it requires significant changes in our API

**Comment by satoshiotomakan** [comment] 2024-07-12 08:03
Hi @ronaldoguedess, yes we plan to add support for X25519 "crypto_box" key exchange protocol to establish TON Connect Session, and also signing a transaction with externally generated data (needed for [sendTransaction](https://github.com/ton-blockchain/ton-connect/blob/main/requests-responses.md))

> Considering that TON Connect currently lacks a JAVA/KOTLIN library, are you planning to develop something to address this gap?

**Comment by ronaldoguedess** [comment] 2024-07-26 04:07
> Hi @ronaldoguedess, yes we plan to add support for X25519 "crypto_box" key exchange protocol to establish TON Connect Session, and also signing a transaction with externally generated data (needed for [sendTransaction](https://github.com/ton-blockchain/ton-connect/blob/main/requests-responses.md))

Is the team working on it? Deadline? I'm asking because this is very important for the moment.

**Comment by satoshiotomakan** [comment] 2024-07-30 09:39
@ronaldoguedess, it's estimated to be done early next week

**Comment by snowkidind** [comment] 2024-08-02 01:43
Just wanted to say that the fix for jettons inadvertently sent to trust wallet was by creating a private key from mnemonic using the derivation path:

`m/44'/607'/${index}'`

**Comment by ronaldoguedess** [comment] 2024-08-02 01:47
> Just wanted to say that the fix for jettons inadvertently sent to trust wallet was by creating a private key from mnemonic using the derivation path:
> 
> `m/44'/607'/${index}'`

I didn't understant, could you give more details?

**Comment by snowkidind** [comment] 2024-08-03 10:56
https://github.com/mytonwalletorg/mytonwallet/issues/62

**Comment by satoshiotomakan** [comment] 2024-08-12 08:18
Hi @ronaldoguedess, X25519 "crypto_box" key exchange protocol is available since [4.1.4](https://github.com/trustwallet/wallet-core/releases/tag/4.1.4)

**Comment by ronaldoguedess** [comment] 2024-08-12 15:22
> Hi @ronaldoguedess, X25519 "crypto_box" key exchange protocol is available since [4.1.4](https://github.com/trustwallet/wallet-core/releases/tag/4.1.4)

Yeah, I saw that, but what can I do with this crypto box? I waiting something to use Ton Connect, or the cypto box is to encrypt memo?

**Comment by satoshiotomakan** [comment] 2024-08-14 12:54
@ronaldoguedess `CryptoBox` is used to establish a TON Session between dapp and the wallet. TON Connect in general is a complex protocol, and WalletCore provides all cryptographic and wallet functions required for its support.
There won't be an TON Connect example in WalletCore as it's out of scope.

**Comment by ronaldoguedess** [comment] 2024-08-15 14:13
> @ronaldoguedess `CryptoBox` is used to establish a TON Session between dapp and the wallet. TON Connect in general is a complex protocol, and WalletCore provides all cryptographic and wallet functions required for its support. There won't be an TON Connect example in WalletCore as it's out of scope.

I understand that. I was hoping you might implement a way to utilize that directly. However, is there at least a way to connect and interact with TON dApps using injection, similar to what the Trust web3-provider does?

I noticed this functionality was added in [this commit](https://github.com/trustwallet/trust-web3-provider/commit/27669692ceace3611d1d592fe8d91430e640063d), but I couldn't find a sample in Java/Kotlin to work with it.

**Comment by satoshiotomakan** [comment] 2024-08-15 15:10
@ronaldoguedess sorry I can't advise on that, better to create a question at the web3-provider repo.
> However, is there at least a way to connect and interact with TON dApps using injection, similar to what the Trust web3-provider does?

**Comment by WayneLaw-Crypto** [comment] 2024-09-19 04:14
Hi, @satoshiotomakan. Ton network has a new feature for jettons, it's about mintless jettons. 
doc: [mintless jettons](https://gist.github.com/EmelyanenkoK/bfe633bdf8e22ca92a5138e59134988f)

I find that trust support custom_payload in Transfer message but not support custom_payload in JettonTransfer message, seems if trust do the support, the mintless jettons transfer can be supported.
Can you add this to your plan?

**Comment by satoshiotomakan** [comment] 2024-09-19 08:13
Hi @WayneLaw-Crypto, thank you for the note. It's on our roadmap already, but low priority at least for now. I'll let you know once we have any ETA

**Comment by satoshiotomakan** [comment] 2024-11-21 10:18
Hi @WayneLaw-Crypto, Mintless Jettons support has been added at https://github.com/trustwallet/wallet-core/pull/4041

**Closed by satoshiotomakan** 2024-11-21 10:18 UTC
